### ISSUE TITLE
link to Hansard source incorrect and only top of tree for Andrew Gee's maiden speech requiring further drilling down

### ISSUE THREAD

**Issue by wwwalker** [openaustralia/openaustralia#608] opened 2016-09-15 03:14 UTC
On Andrew Gee's maiden speech the source of Hansard is incorrect. It only goes to top of tree and does not drill down to his speech. I had to find Governor General's reply and find it there using openaustralia.org.au's content.

Here is Andrew Gee's speech:

http://www.openaustralia.org.au/debate/?id=2016-09-14.47.3&c=1089#c1089

Link to Hansard should be deep link if possible.

given URL from openaustralia Hansard source link:

http://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Date%3A14%2F9%2F2016;rec=0;resCount=Default

correct URL through drilling down using openaustralia title of quote to find right bullet in table of contents on left of Hansard given above:

http://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;adv=yes;db=CHAMBER;id=chamber%2Fhansardr%2Fbf6692fe-063a-41a2-9ebb-5de513f31940%2F0091;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Date%3A14%2F9%2F2016;rec=0;resCount=Default

**Comment by henare** [comment] 2016-09-15 04:14
@wwwalker thanks for reporting this :sparkles: 

I'll close it as it's a duplicate of #289.

**Closed by henare** 2016-09-15 04:14 UTC
